# Default values for guestbook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: gcr.io/google-samples/gb-frontend
  tag: v4
  pullPolicy: Always

resources:
  cpu: 100m
  memory: 100Mi

service:
  type: ClusterIP
  port: 80
