apiVersion: v1
kind: Service
metadata:
  name: {{ include "guestbook.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "guestbook.name" . }}
    helm.sh/chart: {{ include "guestbook.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  type: {{ .Values.service.frontend.type }} 
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  ports:
  - port: {{ .Values.service.frontend.port }}
    targetPort: http-server
  selector:
    app.kubernetes.io/name: {{ include "guestbook.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}