apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    app: redis
    role: slave
    tier: backend
spec:
  type: {{ .Values.service.redismslave.type }} 
  ports:
  - port: {{ .Values.service.redismslave.port }}
    targetPort: {{ .Values.service.redismslave.port }}
  selector:
    app: redis
    role: slave
    tier: backend

