apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
    tier: backend
spec:
  type: {{ .Values.service.redismaster.type }} 
  ports:
  - port: {{ .Values.service.redismaster.port }}
    targetPort: {{ .Values.service.redismaster.port }}
  selector:
    app: redis
    role: master
    tier: backend

